log:
  file:
    name: "projectm"
    dir: "/log"
    maxbytes: 500
    format: "%(asctime)s %(message)s"
    backup_count: 10
run:
  host: "127.0.0.1"
  port: 4801
mongo:
  host: "127.0.0.1"
  port: 27017
  db: "company"